### ISSUE TITLE
엔지넥스 설정파일 정리 필요

### ISSUE THREAD

**Issue by moto6** [Hanghae-Hot6/Back#46]
https://github.com/Hanghae-Hot6/Back/blob/47d5ed44b68d52988bdb11d7dd4be371aa060a17/nginx/conf.d/default.conf#L6

해당 파일또한 asset 하위로 이동하면 좋을듯 싶습니다

**Comment by ryucm** [comment]
옮겼습니다.

**Comment by moto6** [comment]
@ryucm 헛 ㅋㅋ 제 생각에 동의해주셔서 감사합니다! 제가 남긴 모든 피드백은 그냥 참고정도만 해주시고, 창민님께서 생각하시는 타당한 이유가 있다면 그대로 진행하셔도 괜찮습니다~! 마지막까지 화이팅입니닷!!
